# Generated by Django 5.0 on 2024-01-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_id_alter_course_course_name_and_more'),
        ('marksheet', '0001_initial'),
        ('students', '0004_alter_student_exam_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMarksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.IntegerField(default=0)),
                ('section2', models.IntegerField(default=0)),
                ('section3', models.IntegerField(default=0)),
                ('section4', models.IntegerField(default=0)),
                ('section5', models.IntegerField(default=0)),
                ('section6', models.IntegerField(default=0)),
                ('course_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('exam_roll', models.ForeignKey(db_column='exam_roll', on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='exam_roll')),
            ],
        ),
    ]
