# Generated by Django 5.0 on 2024-01-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_roll',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
